### ISSUE TITLE
ModuleNotFoundError: No module named 'google' 

### ISSUE THREAD

**Issue by rahimentezari** [google/caliban#103]
I followed the instructions to install Caliban but running 
caliban run --experiment_config config.json test.py
gives the following error:

  File "/.resources/caliban_launcher.py", line 23, in <module>                                                                                                                    
    import google.auth                                                                                                                                                            
ModuleNotFoundError: No module named 'google'  

I also checked and installed pip install google

update: after install requirement.txt including google-cloud-storage problem is solved

**Comment by sritchie** [comment]
@rahimentezari hey, thanks for the report! What was the fix here?

**Comment by rahimentezari** [comment]
> @rahimentezari hey, thanks for the report! What was the fix here?

update: after install requirement.txt including google-cloud-storage problem is solved
