### ISSUE TITLE
Feature request: Custom base images

### ISSUE THREAD

**Issue by eschnett** [google/caliban#44]
I want to install additional software dependencies into an image, but this software is not available via `apt`, nor is it easy to install. To solve this, I want to run additional Docker stanzas in the image used by Caliban.

One way to do so would be to use a different base image (i.e. `DEV_CONTAINER_ROOT`); in that image, I would start from `gcr.io/blueshift-playground/blueshift` and then add my own software. I put a sample such Dockerfile at <https://gist.github.com/eschnett/5390892b6d8348ea3be5ca35d95f4990>.

Alternatively, one could specify these stanzas in `.calibanconfig.json`.

I tried the `--image_id` option, but this doesn't work. It works for `caliban shell`, but for `caliban run` it skips packing up the current directory.

**Comment by sritchie** [comment]
Here's the PR where I implemented this: https://github.com/google/caliban/pull/39
