### ISSUE TITLE
`caliban cloud`: providing project ID through CLI fails

### ISSUE THREAD

**Issue by arokem** [google/caliban#51]
I am seeing: 

```
$caliban cloud --nogpu mnist.py -- --project_id landscape-238422


No project_id found. 'caliban cloud' requires that you either set a 
$PROJECT_ID environment variable with the ID of your Cloud project, or pass one 
explicitly via --project_id. Try again, please!

```

Setting the environment variable does seem to work.

**Comment by sritchie** [comment]
Ah, yes, @arokem that is a subtlety with the argument parsing. Anything that comes after `--` is assumed to be an arg you want to pass directly into the container, to your script.

If you did this instead:

```
caliban cloud --nogpu --project_id landscape-238422 mnist.py
```

you should see it work out.

I'll be releasing an update today that removes the need for a service account key, which should make it slightly easier to get started.

let me know if this helps! Glad you got unblocked with the env variable.
