### ISSUE TITLE
Create base image based on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by eschnett** [google/caliban#54]
I need to use several software packages that are either not available in Ubuntu 18.04, or are outdated there. It would be quite convenient for me if the base image was using Ubuntu 20.04LTS instead of 18.04LTS.

For reference, I need these packages which are not available in 18.04:
- cmake >= 3.14
- gcc >= 8
- libopenmpi-dev >= 3
- libpsm2

I can, of course, install these from source, but this is time consuming every time the image is rebuilt.

**Comment by ajslone** [comment]
@eschnett I have a PR in to add this to our cloudbuild script (https://github.com/google/caliban/pull/78), and I manually generated cpu images for 20.04 if you'd like to give it a try: `gcr.io/blueshift-playground/blueshift:cpu-ubuntu2004-py37` and `gcr.io/blueshift-playground/blueshift:cpu-ubuntu2004-py38`

**Comment by eschnett** [comment]
@ajslone I tried the `py38` version, and I like it. My Dockerfile is now half the size. Thanks a lot!
